apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-hyperconverged-manager
rules:
  - apiGroups: ["hco.kubevirt.io"]
    resources:
      - hyperconvergeds
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - label
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-hyperconverged-manager-binding
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-hyperconverged-manager